[dev]
  command = "npm run dev" 

[functions]
  directory = "netlify/functions"  

[context.production.environment]
  NODE_VERSION = "20.11.1"  

[context.production]
  command = "node server/server.js" 
  publish = "front-end"