[build] 
  command = "npm run build" 
  publish = "front-end"      

[dev]
  command = "npm run start" 

[functions]
  directory = "netlify/functions"  

[context.production.environment]
  NODE_VERSION = "14"  

[context.production]
  command = "node server/server.js" 
  publish = "front-end"